language: python
sudo: false

matrix:
    include:
        - env: TOXENV=py27
        - env: TOXENV=py33
        - env: TOXENV=py34
        - env: TOXENV=pypy
        - env: TOXENV=docs
          addons:
              apt:
                  packages:
                      - libenchant-dev
        - env: TOXENV=pep8
        - env: TOXENV=py3pep8

install:
    - pip install coveralls tox
    - |
        if [ "${TOXENV}" == "pypy" ]
        then
            git clone --depth 1 https://github.com/yyuu/pyenv.git ~/.pyenv
            PYENV_ROOT="$HOME/.pyenv"
            PATH="$PYENV_ROOT/bin:$PATH"
            eval "$(pyenv init -)"
            pyenv install pypy-4.0.1
            pyenv global pypy-4.0.1
        fi

script:
    - tox
    - |
        SPELLING_OUTPUT=/home/travis/build/pyca/tls/docs/_build/html/output.txt
        if [ -f $SPELLING_OUTPUT ]
        then
            cat $SPELLING_OUTPUT
        fi

after_success:
    - coveralls

notifications:
    irc:
        channels: "irc.freenode.net#cryptography-dev"
        use_notice: true
        skip_join: true
