language: python
sudo: false

matrix:
    include:
        - env: TOXENV=py26
        - env: TOXENV=py27
        - env: TOXENV=py32
        - env: TOXENV=py33
        - env: TOXENV=py34
        - env: TOXENV=pypy
        - env: TOXENV=docs
          addons:
              apt:
                  packages:
                      - libenchant-dev
        - env: TOX_ENV=pep8
        - env: TOX_ENV=py3pep8

install:
    - pip install coveralls tox

script:
    - tox

after_success:
    - coveralls

notifications:
    irc:
        channels: "irc.freenode.net#cryptography-dev"
        use_notice: true
        skip_join: true
